from enum import Enum


class StrEnum(str, Enum):
    """String-backed enum for clean JSON serialization."""


class UserRole(StrEnum):
    PROVINCE = "PROVINCE"
    CITY = "CITY"
    ENTERPRISE = "ENTERPRISE"


class FilingStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ReviewStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_CITY_REVIEW = "PENDING_CITY_REVIEW"
    PENDING_PROVINCE_REVIEW = "PENDING_PROVINCE_REVIEW"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"
    REPORTED_TO_MINISTRY = "REPORTED_TO_MINISTRY"


class AuditAction(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class AnalysisDimension(StrEnum):
    REGION = "REGION"
    ENTERPRISE_NATURE = "ENTERPRISE_NATURE"
    INDUSTRY = "INDUSTRY"


class ExchangeDirection(StrEnum):
    EXPORT = "EXPORT"
    IMPORT = "IMPORT"


class PermissionCode(StrEnum):
    ENTERPRISE_INFO_EDIT = "ENTERPRISE_INFO_EDIT"
    ENTERPRISE_FILING_SUBMIT = "ENTERPRISE_FILING_SUBMIT"
    ENTERPRISE_REPORT_SUBMIT = "ENTERPRISE_REPORT_SUBMIT"
    ENTERPRISE_REPORT_QUERY = "ENTERPRISE_REPORT_QUERY"
    PASSWORD_CHANGE = "PASSWORD_CHANGE"
    CITY_REPORT_AUDIT = "CITY_REPORT_AUDIT"
    CITY_NOTICE_MANAGE = "CITY_NOTICE_MANAGE"
    PROVINCE_FILING_REVIEW = "PROVINCE_FILING_REVIEW"
    PROVINCE_ENTERPRISE_QUERY = "PROVINCE_ENTERPRISE_QUERY"
    PROVINCE_REPORT_MANAGE = "PROVINCE_REPORT_MANAGE"
    PROVINCE_DATA_MODIFY = "PROVINCE_DATA_MODIFY"
    PROVINCE_DATA_DELETE = "PROVINCE_DATA_DELETE"
    PROVINCE_DATA_SUMMARY = "PROVINCE_DATA_SUMMARY"
    PROVINCE_DATA_EXPORT = "PROVINCE_DATA_EXPORT"
    PROVINCE_MULTI_ANALYSIS = "PROVINCE_MULTI_ANALYSIS"
    PROVINCE_CHART_ANALYSIS = "PROVINCE_CHART_ANALYSIS"
    NOTICE_BROWSE = "NOTICE_BROWSE"
    NOTICE_MANAGE = "NOTICE_MANAGE"
    REPORTING_WINDOW_MANAGE = "REPORTING_WINDOW_MANAGE"
    USER_MANAGE = "USER_MANAGE"
    ROLE_MANAGE = "ROLE_MANAGE"
    SYSTEM_MONITOR = "SYSTEM_MONITOR"
    NATIONAL_EXCHANGE = "NATIONAL_EXCHANGE"


class ReductionType(StrEnum):
    CLOSED_BANKRUPT = "关闭破产"
    SUSPENSION_REORGANIZATION = "停业整顿"
    ECONOMIC_LAYOFF = "经济性裁员"
    BUSINESS_TRANSFER = "业务转移"
    NATURAL_ATTRITION = "自然减员"
    NORMAL_CONTRACT_TERMINATION = "正常解除或终止劳动合同"
    INTERNATIONAL_FACTORS = "国际因素变化影响"
    NATURAL_DISASTER = "自然灾害"
    MAJOR_EVENT = "重大事件影响"
    OTHER = "其他"


class ReductionReason(StrEnum):
    INDUSTRIAL_RESTRUCTURING = "产业结构调整"
    TECHNOLOGICAL_REFORM = "重大技术改革"
    ENERGY_SAVING_AND_CAPACITY_REDUCTION = "节能减排、淘汰落后产能"
    INSUFFICIENT_ORDERS = "订单不足"
    RAW_MATERIAL_PRICE_RISE = "原材料涨价"
    LABOR_COST_RISE = "工资、社保等用工成本上升"
    FUNDING_DIFFICULTY = "经营资金困难"
    TAX_POLICY_CHANGE = "税收政策变化（包括税负增加或出口退税减少等）"
    SEASONAL_EMPLOYMENT = "季节性用工"
    OTHER = "其他"
    VOLUNTARY_RESIGNATION = "自行离职"
    JOB_TRANSFER_AND_INTERNAL_REALLOCATION = "工作调动、企业内部调剂"
    LABOR_RELATION_TRANSFER_AND_DISPATCH = "劳动关系转移、劳务派遣"
    RETIREMENT = "退休"
    RESIGNATION = "退职"
    DEATH = "死亡"
    NATURAL_ATTRITION = "自然减员"
    INTERNATIONAL_FACTORS = "国际因素变化"
    RECRUITMENT_DIFFICULTY = "招不上人来"
